spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/jwt
        username: postgres
        password: eno
        driver-class-name: org.postgresql.Driver
    jpa:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      hibernate:
        ddl-auto: create-drop

application:
  security:
    jwt:
      secret-key: 6B5970337336763979244226452948404D6351655468576D5A7134743777217A
      expiration: 60000 # 1 minute
      refresh-token:
        expiration: 604800000 # 7 days